function result = add_bn(name, bottom, top, bn_stat, train_param)
    assert(nargin >= 4);
    if nargin <= 4, train_param = true; end;
    
    blobs_lr = iif(train_param, 1, 0);
    
    bn_stat = struct('value', bn_stat);
    result = builder.layers.add_layer( ...
        name, 'batch_norm', bottom, top, ...
        {'batch_norm_param', { ...
            'scale_filler', { 'type', 'constant', 'value', 1 }, ...
            'shift_filler', { 'type', 'constant', 'value', 0 }, ...
            'record_option', bn_stat, ...
            } ...
        }, ...
        'blobs_lr', blobs_lr, ...
        'blobs_lr', blobs_lr, ...
        'blobs_lr', 0, ...
        'blobs_lr', 0, ...
        'weight_decay', 0, ...
        'weight_decay', 0, ...
        'weight_decay', 0, ...
        'weight_decay', 0 ...
        );
end

