function result = add_pool(name, bottom, top, pool, ksize, stride, pad, size_floor)
    assert(nargin >= 6);
    if nargin <= 6, pad = 0; end;
    if nargin <= 7, size_floor = false; end;
    pool = struct('value', pool);
    size_floor = iif(size_floor, 'true', []);
    
    result = builder.layers.add_layer( ...
        name, 'pool', bottom, top, ...
        {'pool_param', { ...
            'kernel_size', ksize, ...
            'stride', stride, ...
            'pool', pool, ...
            'pad', iif(pad ~= 0, pad, []), ...
            'size_floor', size_floor, ...
            } ...
        } ...
        );
end

