function result = add_prelu(name, bottom, top, init_value)
    result = builder.layers.add_layer( ...
        name, 'prelu', bottom, top, ...
        {'learnable_leak_relu_param', { ...
            'share_param', struct('value', 'CHANNEL'), ...
            'relu_leak_param', { ...
                'type', 'constant', ...
                'value', init_value, ...
                } ...
            } ...
        } ...
        );
end

