function result = add_instance_sample(name, bottom, top, num, method)
    assert(nargin >= 4);
    if nargin <= 4, method = 'SEQ'; end;
    method = struct('value', method);
    
    result = builder.layers.add_layer(name, 'instance_sample', bottom, top, ...
        {'instance_sample_param', { ...
            'sample_method', method, ...
            'num', num
            }
        }, ...
        'blobs_lr', 0 ...
        );
end

