function result = add_mn(name, bottom, top, bn_stat)
    bn_stat = struct('value', bn_stat);
    result = builder.layers.add_layer( ...
        name, 'mean_norm', bottom, top, ...
        {'batch_norm_param', { ...
            'scale_filler', { 'type', 'constant', 'value', 0 }, ...
            'shift_filler', { 'type', 'constant', 'value', 0 }, ...
            'record_option', bn_stat, ...
            } ...
        }, ...
        'blobs_lr', 1, ...
        'blobs_lr', 0, ...
        'weight_decay', 0, ...
        'weight_decay', 0 ...
        );
end

