function result = add_correlation(name, bottom, top, stride, pad, has_bias, varargin)
    assert(nargin >= 6);
    opt = struct();
    if nargin >= 7, opt = varargin{1}; end;
    
    if ~isfield(opt, 'bias_filler'), opt.bias_filler = {'type', 'constant', 'value', 0}; end;
    
    result = builder.layers.add_layer( ...
        name, 'correlation', bottom, top, ...
        {'correlation_param', { ...
            'pad', pad, ...
            'stride', stride, ...
            iif(has_bias, {'bias_filler', opt.bias_filler}, []), ...
            'bias_term', iif(has_bias, [], 'false'), ...
            }, ...
        }, ...
        iif(has_bias, {'blobs_lr', 1}, []) ...
        );
end

