function result = add_step_gate(name, bottom, top, init_v, step_v, max_v, keep_backward, keep_forward, start_iter)
    assert(nargin >= 6);
    if nargin <= 6, keep_backward = []; end;
    if nargin <= 7, keep_forward = []; end;
    if nargin <= 8, start_iter = []; end;

    if ~isempty(keep_backward)
        keep_backward = iif(keep_backward, 'true', 'false');
    end
    if ~isempty(keep_forward)
        keep_forward = iif(keep_forward, 'true', 'false');
    end

    result = builder.layers.add_layer( ...
        name, 'step_gate', bottom, top, ...
        {'step_gate_param', { ...
            'init_value', init_v, ...
            'step_value', step_v, ...
            'max_value', max_v, ...
            'keep_backward', keep_backward, ...
            'keep_forward', keep_forward, ...
            'start_iter', start_iter, ...
            } ...
        }, ...
        'blobs_lr', 0 ...
        );
end

