function result = add_diag4d_operation(name, bottom, top, scale, shift)
    result = builder.layers.add_layer( ...
        name, 'diag4d_operation', bottom, top, ...
        {'diag_operation_param', { ...
            'scale', scale, ...
            'shift', shift
            } ...
        } ...
        );
end

